{*****************************************************************************

 Pascal Object Environment Library

 Description : Pascal Object Environment Library is inspireed from somes inc
               configuration files of many libraries likes JediVCL for exemple.

 Author(s) : Frédéric Libaud

 File : poenv.inc

        Principal include file for POE library
 =============================================================================
 History :

 *****************************************************************************}

{$ifdef LAZARUS}
  {$i poe_lclversionlazarus.inc}
{$endif}

{$ifdef TYPHON}
  {$i poe_lclversiontyphon.inc}
{$endif}


